
# Human experiments

## Human volunteers

### Restraint systems

- [@Reed2019] : Posture and belt fit in reclined passenger seats

> Regression analysis demonstrated that the pelvis rotated rearward and lumbar spine flexion decreased with increasing recline. The lap portion of the 3-point belt was more rearward relative to the pelvis in more-reclined postures, and the torso portion crossed the clavicle closer to the midline of the body. Regression equations were developed to predict posture and belt fit variables as a function of passenger characteristics, seat back angle, and the use of the headrest.

### Precrash

- @Graci2019: Effect of automated versus manual emergency braking on rear seat adult and pediatric occupant precrash motion

- @Ghaffari2019: Passenger muscle responses in lane change and lane change with braking maneuvers using two belt configurations: Standard and reversible pre-pretensioner


## Post-mortem human subjects (PMHS)

- @Richardson2019 : Test Methodology for Evaluating the Reclined Seating Environment With Human Surrogates

- Kang, 2018, IRCOBI : Head neck PMHS, frontal, oblique, side and twist scenarios

- Shurtz et al., 2018, Small female side impact

- @Shaw2009 :  Impact Response of Restrained (PMHS) in Frontal Sled Tests: Skeletal Deformation Patterns Under Seat Belt Loading




## Dummies

- [@Viano2018]: Rear-seat occupant in rear crash test (NHTSA)

- Parent et al., 2017, Stapp, THOR vs HIII 50th male in frontal impact

## Biofidelity

- A Methodology for Generating Objective Targets for Quantitatively Assessing the Biofideltiy of crash test dummies [@Rhule2009]
