--- 
title: "Literature Collection: HBM and Injury Prevention"
author: "Jobin"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [manual-ref.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "A collection a scientific literature on Injury Prevention, with a focus on Human Body Models.  The output format for this example is bookdown::gitbook."
---

# Introduction 



<!--chapter:end:index.Rmd-->

# Human Body Models 

## Rear Impact

- @Katagiri2019: Biofidelity Evaluation of GHBMC Male Occupant Models in Rear Impact

> The NHTSA Biofidelity Ranking System was used to evaluate the HBMs. The HBMs exhibited better biofidelity 1) at 17 km/h than 24 km/h, and 2) in the head to T1 region, which is relevant to rear-impact-related injuries, than the T1 to pelvis region. The detailed HBM received a better biofidelity score than the simplified HBM in every studied component. Limitations for the HBMs’ biofidelity were indicated in the modelling of their spines and surrounding flesh.


## Frontal impact

- @Tang2020: A numerical investigation of factors affecting lumbar spine injuries in frontal crashes #HIII

> Parametric simulations were conducted using a set of validated vehicle driver compartment model, restraint system model, and a HIII mid-size male crash test dummy model. Risk factors considered in the study included occupant seating posture, crash pulse, vehicle pitch angle, seat design, anchor pre-tensioner, dynamic locking tongue, and shoulder belt load limiter. 



- @Devane2019: Validation of a simplified human body model in relaxed and braced conditions in low-speed frontal sled tests #GHBMC

- @Hu2019: Frontal crash simulations using parametric human models representing a diverse population

> Frontal crash simulations based on U.S. New Car Assessment Program (U.S. NCAP) were conducted. Body region injury risks were calculated based on the risk curves used in the US NCAP, except that scaling was used for the neck, chest, and knee–thigh–hip injury risk curves based on the sizes of the bony structures in the corresponding body regions. Age effects were also considered for predicting chest injury risk.
>
Results: The simulations demonstrated that driver stature and body shape affect occupant interactions with the restraints and consequently affect occupant kinematics and injury risks in severe frontal crashes. U-shaped relations between occupant stature/weight and head injury risk were observed. Chest injury risk was strongly affected by age and sex, with older female occupants having the highest risk. A strong correlation was also observed between BMI and knee–thigh–hip injury risk, whereas none of the occupant parameters meaningfully affected neck injury risks.

## Side Impact

- @PerezRapela2020: Methodology for the Evaluation of Human Response Variability to Intrinsic and Extrinsic Factors Including Uncertainties

- @Hwang2019: Diverse Human Body Models against Side Impact Tests with Post-Mortem Human Subjects
    + Dual-sled model validated with SID, SID-II: @Hwang2016 (Development, Evaluation, and Sensitivity Analysis of Parametric Finite Element Whole-Body Human Models in Side Impacts)
    

> With weight, stature, sex, and age of PMHS, seven FE HBMs were developed by morphing the midsize male THUMS model into the target geometries predicted by the statistical skeleton and external body shape models. The model-predicted force histories, accelerations a long the spine, and deflections in the chest and abdomen were compared to the test data. For comparison, simulations in all testing conditions were also conducted with the original midsize male THUMS, and the results from the THUMS simulations were scaled to the weight and stature from each PMHS. 

[@Hwang2019]

## Oblique Impact


- @Perez-rapela2019: Comparison of the simplified GHBMC to PMHS kinematics in far-side impact

> Results  show  that,  in  general,  the  simplified  GHBMC  captures  lateral  excursion  in  oblique  impact conditions but overpredicts in purely lateral impact conditions. The simplified GHBMC shows post-mortem human subject like sensitivities to changes in ΔV  and  the  use  of  pretensioner  but  no  sensitivity  to  changes  in  impact direction. The human body model performs similarly to other previously published HBMs and obtains a “good”  CORA  score.  However,  the  surrogate  does  not  represent  post-mortem  human  subject  shoulder-to-belt interaction in all configurations. 

## Vulnerable population

- @Larsson2019: Evaluation of the Benefits of Parametric Human Body Model Morphing for Prediction of Injury to Elderly Occupants in Side Impact    

> Side-impact sled tests conducted  with  these  PMHS  were  recreated  by  means  of  simulations  with  the  baseline  and  morphed  HBMs.  Results  showed  that  the  parametrically  morphed  models  showed  improved  correlation  with  PMHS  kinematics  compared  with  the  baseline  HBM  predictions  and  performed  as  well  as  the  further  personalized  models.  Both  parametric and personalized HBMs failed to predict the PMHS chestband deflection magnitudes and predicted no risk for rib fractures. In contrast, both PMHS sustained multiple fractured ribs during testing. In conclusion, parametric  HBM morphing alone improved  prediction  of  individual  kinematics, but neither  morphing  method improved individual injury risk prediction.

## Future Seat Configurations

- @Boyle2019: A Human Modelling Study on Occupant Kinematics in Highly Reclined Seats during Frontal Crashes 

- @Rawska2019: Submarining sensitivity across varied anthropometry in an autonomous driving system environment

<!--chapter:end:01-HBM.Rmd-->


# Human experiments

## Human volunteers

- @Higuchi2019: Behavior of ATD, PMHS and Human Volunteer in Frontal Crash Test

> We accessed high speed human volunteer test data which had completed in the 1970's in United States sponsored by National Highway Traffic Safety Administration (NHTSA) from NHTSA`s archives. In this report we compared these high speed human volunteer test results with our previous work and concluded the excursion of human volunteer is less than the excursion of PMHS at higher speeds, mimicking the findings at lower speeds. 



### Restraint systems

- [@Reed2019] : Posture and belt fit in reclined passenger seats

> Regression analysis demonstrated that the pelvis rotated rearward and lumbar spine flexion decreased with increasing recline. The lap portion of the 3-point belt was more rearward relative to the pelvis in more-reclined postures, and the torso portion crossed the clavicle closer to the midline of the body. Regression equations were developed to predict posture and belt fit variables as a function of passenger characteristics, seat back angle, and the use of the headrest.

### Precrash

- @Graci2019: Effect of automated versus manual emergency braking on rear seat adult and pediatric occupant precrash motion

- @Ghaffari2019: Passenger muscle responses in lane change and lane change with braking maneuvers using two belt configurations: Standard and reversible pre-pretensioner


## Post-mortem human subjects (PMHS)

- @Richardson2019 : Test Methodology for Evaluating the Reclined Seating Environment With Human Surrogates

- Kang, 2018, IRCOBI : Head neck PMHS, frontal, oblique, side and twist scenarios

- Shurtz et al., 2018, Small female side impact

- @Shaw2009 :  Impact Response of Restrained (PMHS) in Frontal Sled Tests: Skeletal Deformation Patterns Under Seat Belt Loading




## Dummies

- @Whyte2019: Frontal crash seat belt restraint effectiveness and comfort accessories used by older occupants


- @Viano2018: Rear-seat occupant in rear crash test (NHTSA)

- Parent et al., 2017, Stapp, THOR vs HIII 50th male in frontal impact

## Biofidelity

- A Methodology for Generating Objective Targets for Quantitatively Assessing the Biofideltiy of crash test dummies [@Rhule2009]

<!--chapter:end:02-experiments.Rmd-->

# Head

- @Bruneau2019: Head and Neck Response of an Active Human Body Model and Finite Element Anthropometric Test Device During a Linear Impactor Helmet Test

> Although responses that develop over longer durations following the impact differed slightly, such as the moment at the base of the neck, this occurred later in time, and therefore, did not considerably affect the short-term head kinematics in the primary impact direction. Though muscle activation did not play a strong role in the head response for the test configurations considered, muscle activation may play a role in longer duration events.


- @Miller2019: An envelope of linear and rotational head motion during everyday activities

> The peak resultant linear accelerations of the head reported in the literature were all less than 15 g, while the peak resultant rotational accelerations and rotational velocities approach 1375 rad/s2 and 12.8 rad/s, respectively.

- @Chang2019: Evaluation of Human Nasal Cartilage Nonlinear and Rate Dependent Mechanical Properties

## Brain


### Models

- @Wang2018: quantitative analysis of the effects of boundary conditions and brain tissue constitutive model, Prediction of brain deformations and risk of traumatic brain injury due to closed-head impact
#THUMS4

> The brain–skull interface models included direct representation of the brain meninges and cerebrospinal fluid, outer brain surface rigidly attached to the skull, frictionless sliding contact between the brain and skull, and a layer of spring-type cohesive elements between the brain and skull. We considered Ogden hyperviscoelastic, Mooney–Rivlin hyperviscoelastic, neo–Hookean hyperviscoelastic and linear viscoelastic constitutive models of the brain tissue. Our study indicates that the predicted deformations within the brain and related brain injury criteria are strongly affected by both the approach of modelling the brain–skull interface and the constitutive model of the brain parenchyma tissues. 


### Experiments

- @Li2019: A Comprehensive Study on the Mechanical Properties of Different Regions of 8-week-old Pediatric Porcine Brain under Tension, Shear, and Compression at Various Strain Rates



### Sports

- @Kent2019: The Biomechanics of Concussive Helmet-to-Ground Impacts in the National Football League

> Video analysis was performed for 16 head-to-ground impacts that caused concussions. Average resultant closing velocity was 8.3 m/s at an angle nearly 45° to the surface. Preimpact rotational velocity of the helmet ranged from negligible to as high as 54.1 rad/s. Helmet impacts were concentrated on the posterior and lateral aspects.


<!--chapter:end:03-Head.Rmd-->

# Spine

- @Zhang2020: Moment-rotation behavior of intervertebral joints in flexion-extension, lateral bending, and axial rotation at all levels of the human spine: A structured review and meta-regression analysis

- @Afquir2020: Descriptive analysis of the effect of back protector on the prevention of vertebral and thoracolumbar injuries in serious motorcycle accident


- @Nishida2019: Changes in the Global Spine Alignment in the Sitting Position in an Automobile

> Changing posture from standing to sitting decreased CL by an average of 5.3°, slightly decreased TK by an average of 1.3°, increased TLK by an average of 6.8°, decreased LL by an average of 35°, decreased SS by an average of 49.2°, increased PT by an average of 49.2°, shifted C7-SVA backward by an average of 106.7 mm, decreased T1SPI by an average of 18.8°, and increased TPA by an average of 21.1°. 

- @Simond2019: Discovery of a New Ligament of the Lumbar Spine: The Midline Interlaminar Ligament

> Twenty-six out of thirty-four (76.5%) lumbar levels were found to have a MIL traveling on the internal aspect of the most medial aspect of the laminae and positioned slightly anterior to the plane of the ligamenta flava.
The mean length and width of the MIL were 9.03±4.29 mm and 4.94±1.56 mm, respectively. The mean force necessary until failure for the MIL was 12.3N.


- @Sato2019: Relationship Between Cervical, Thoracic and Lumbar Spinal Alignments in Automotive Seated Posture

## Cervical Spine

- @Tisherman2019:  Biomechanical Contribution of the Alar Ligaments to Upper Cervical Stability

> The alar ligaments also contributed to resistance to intact motion in extension (13.4 ± 6.6%, p < 0.05), flexion (4.4 ± 2.2%, p < 0.05), axial rotation (19.3 ± 2.7%, p < 0.05), and lateral bending (16.0 ± 2.8%, p < 0.05). 

- @Zhou2019 : Intervertebral Range of Motion Characteristics of Normal Cervical Spinal Segments (C0-T1) during In Vivo Neck  (dual fluroscopy)  
Related papers
  - @Wang2008: Measurement of Vertebral Kinematics Using Noninvasive Image Matching Method–Validation and Application
  - @Yu2017: Ranges of Cervical Intervertebral Disc Deformation During an In Vivo Dynamic Flexion–Extension of the Neck

## Thoracic Spine


## Lumbar Spine

Lumbar spine injuries in frontal collision

- @Kaufman2013: Burst fractures of the lumbar spine in frontal crashes

- @Pintar2012: Thoracolumbar Spine Fractures in Frontal Impact Crashes 

<!--chapter:end:04-Spine.Rmd-->

# Shoulder and Upper Extremity



## Shoulder

- @Mulla2019: Glenohumeral stabilizing roles of the scapulohumeral muscles: Implications of muscle geometry


- @Kian2019: Static optimization underestimates antagonist muscle activity at the glenohumeral joint: A musculoskeletal modeling study

- @Bouaicha2019: Biomechanical analysis of the humeral head coverage, glenoid inclination and acromio-glenoidal height as isolated components of the critical shoulder angle in a dynamic cadaveric shoulder model

> All three components (acromial coverage, glenoid inclination or acromial height) had an effect on either muscle forces and or joint reaction forces. While glenoid inclination showed the highest impact on joint stability with increasing upward-tilting causing cranial subluxation, changing of the lateral acromial coverage or acromial height had less influence on stability but showed significant alteration of joint reaction forces.

- @Cudlip2019: The ability of surface electromyography to represent supraspinatus anterior and posterior partition activity depends on elevation angle, hand load and plane of elevation



## Upper Extremity

<!--chapter:end:05-Upper-Extremity.Rmd-->

# Thorax



## Rib injuries

- @Katzenberger2020: Effects of sex, age, and two loading rates on the tensile material properties of human rib cortical bone 

> There were no significant differences in material properties between sexes and no significant interactions between age and sex.

>Spearman correlation analyses showed that all material properties had significant negative correlations with age at 0.005 strain/s except modulus. At 0.5 strain/s, all material properties except yield strain had significant negative correlations with age. Although the results revealed that the material properties of human rib cortical bone varied significantly with respect to chronological age, the R2 values only ranged from 0.15 to 0.62, indicating that there may be other underlying variables that better account for the variance within a given population. 

- @Iraeus2019: Detailed subject-specific FE rib modeling for fracture prediction 


- @Ramachandra2019: GHBMC M50-O:Evaluation of Skeletal and Soft Tissue Contributions to Thoracic Response, Dynamic Frontal Loading Scenarios 
  - Experimental data: [@Murach2018]

- Human Rib Fracture Characteristics and Relationships with Structural Properties [@Harden2019]

> Ribs (n=347) were impacted in a dynamic bending scenario representing a frontal thoracic impact. Fracture characteristics (location, classification, number, and severity) were analyzed utilizing a new classification system. 
Structural properties (peak and yield force, %peak and yield displacement, linear structural stiffness, total energy, plastic energy, and ductility/brittleness) were calculated from test data for each rib and their relationships with fracture characteristics were assessed. Three structural properties (%peak displacement, total energy, and plastic energy) were found to have significant differences with all fracture characteristics except fracture location. However, the significant differences were only found in specific comparisons within each fracture characteristic. Fracture location was only found to have a significant relationship with % peak displacement.




## Internal organ injuries

<!--chapter:end:06-Thorax.Rmd-->

# Abdomen and Pelvis


## Abdomen

- Ramachandra 2016, Stapp, PMHS abdominal seat belt loading
- Howes et al., 2012, Stapp, PMHS experiments using biplanar X-rays, thoracoabdominal contents
- Lamielle et al., 2008, Stapp, 3D deformation and dynamics of the human cadaver abdomen under seatbelt loading


## Pelvis

- @Casaroli2019: What do we know about the biomechanics of the sacroiliac joint and of sacropelvic fixation? A literature review

> Additionally, this study aims to support biomechanical investigations in defining experimental protocols as well as numerical modeling of the sacropelvic structures. The sacroiliac joint is characterized by a large variability of shape and ranges of motion among individuals. Although the ligament network and the anatomical features strongly limit the joint movements, sacroiliac displacements and rotations are not negligible.


- @Yoganandan2019: Pelvis injury risk curves in **side impacts** from human cadaver experiments using survival analysis and Brier score metrics

## Adipose Tissue

- Abdominal and breast adipose tissue viscoelastic properties [@Calvo-Gallego2019]

<!--chapter:end:07-Abdomen-Pelvis.Rmd-->

# Lower Extremities

- @Derrick2019: ISB recommendations on the reporting of intersegmental forces and moments during human motion analysis

- @McMurry2019: Evaluating the influence of knee airbags on lower limb and whole-body injury

## Morphology

- @Audenaert2019: Lower extremity statistical shape models, Gender differences, asymmetry

## Knee Joint

- @Cooper2019: Finite element models of the tibiofemoral joint: A review of validation approaches and modelling challenges

> This review provides an overview of the challenges involved in developing finite element models of the tibiofemoral joint, including the representation of appropriate geometry and material properties, loads and motions, and establishing pertinent outputs.

<!--chapter:end:08-Lower-Extremities.Rmd-->

# Miscellaneous

## Muscles

Tamura 2019: Elastic tensile behavior of [muscle fiber bundles in traumatic loading conditions](https://www.sciencedirect.com/science/article/pii/S0268003318307083)

Neumann 2019: Regional variations of in vivo surface stiffness of [soft tissue layer in extremities](https://www.sciencedirect.com/science/article/pii/S0021929019305135?dgcid=raven_sd_aip_email)


## Soft Tissues

- @Chen2019: Inverse finite element characterization of the human thigh soft tissue in the seated position


<!--chapter:end:09-Misc.Rmd-->

# Future of Transport

- @Selvik2020: Can the use of road safety measures on national roads in Norway be interpreted as an informal application of the {ALARP} principle?


- @Mindell2019: Changing aspirations: The future of transport and health (editorial)


<!--chapter:end:10-Policy-Forecast-etc.Rmd-->

`r if (knitr:::is_html_output()) '
# References {-}
'`

<!--chapter:end:11-references.Rmd-->

